# Build Options
#   change yes to no to disable
#

DEFAULT_FOLDER = crkbd/rev1

RGBLIGHT_SUPPORTED = yes
RGB_MATRIX_SUPPORTED = yes
COMBO_ENABLE = yes
POINTING_DEVICE_ENABLE = yes
POINTING_DEVICE_DRIVER = cirque_pinnacle_i2c
#BOOTMAGIC_ENABLE = no
#SLEEP_LED_ENABLE = no
#NKRO_ENABLE = no
LTO_ENABLE = yes
#CONSOLE_ENABLE = no
#COMMAND_ENABLE = no
#MOUSEKEY_ENABLE = no
#EXTRAKEY_ENABLE = no
#SPACE_CADET_ENABLE = no
#GRAVE_ESC_ENABLE = no 
#MAGIC_ENABLE = no